--바디 시퀀스 삭제 및 초기화
DROP SEQUENCE body_seq;
-- 시퀀스 생성
CREATE SEQUENCE body_seq START WITH 1 INCREMENT BY 1;
--테이블 생성

CREATE TABLE body (
    idx NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    target_weight NUMBER(4, 1),
    target_calories NUMBER(5),
    weight NUMBER(4, 1) NOT NULL,
    height NUMBER(3) NOT NULL,
    age NUMBER(3),
    gender CHAR(1),
    inbody NUMBER(5, 2),
    record_date DATE NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customers(idx) ON DELETE CASCADE
);

SELECT * FROM body;
