-- SELECT
SELECT * FROM customers;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = "tabnam";
-- DROP
DROP TABLE customers;
DROP TABLE body;
DROP TABLE foodInfo;
DROP TABLE goal;

--커밋
commit;
-- 각 테이블 조회
SELECT * FROM customers;
SELECT * FROM goal;
SELECT * FROM foodInfo;
-- SQL 버전보기
SELECT * FROM V$VERSION;

-- 외래 키에 의해 종속된 테이블 먼저 삭제
DROP TABLE goal CASCADE CONSTRAINTS;
DROP TABLE body CASCADE CONSTRAINTS;

-- 마지막으로 customers 테이블 삭제
DROP TABLE customers CASCADE CONSTRAINTS;

--테이블 수정된걸로 수정
CREATE TABLE customers (
    idx NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    weight NUMBER(4, 1),
    age NUMBER(3),
    gender CHAR(1) CHECK (gender IN ('M', 'F')),
    height NUMBER(3)
);

-- customers 시퀀스 생성
CREATE SEQUENCE customers_seq START WITH 1 INCREMENT BY 1;


CREATE TABLE goal (
    idx NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    target_weight NUMBER(4, 1) NOT NULL,
    target_calories NUMBER(5) NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customers(idx) ON DELETE CASCADE
);

CREATE TABLE body (
    idx NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    target_weight NUMBER(4, 1),
    target_calories NUMBER(5),
    weight NUMBER(4, 1) NOT NULL,
    height NUMBER(3) NOT NULL,
    age NUMBER(3),
    gender CHAR(1),
    inbody NUMBER(5, 2),
    record_date DATE NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customers(idx) ON DELETE CASCADE
);