-- SELECT
SELECT * FROM customers;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = "tabnam";

--커밋
commit;
-- 각 테이블 조회
SELECT * FROM customers;
SELECT * FROM goal;
SELECT * FROM foodInfo;
-- SQL 버전보기
SELECT * FROM V$VERSION;

-- 외래 키에 의해 종속된 테이블 먼저 삭제
DROP TABLE goal CASCADE CONSTRAINTS;
DROP TABLE body CASCADE CONSTRAINTS;
DROP TABLE recovery CASCADE CONSTRAINTS;
DROP TABLE record CASCADE CONSTRAINTS;

-- 마지막으로 customers 테이블 삭제
DROP TABLE customers CASCADE CONSTRAINTS;
-- 시퀀스 초기화
drop SEQUENCE customers_seq;
-- customers 시퀀스 생성
CREATE SEQUENCE customers_seq START WITH 1 INCREMENT BY 1;

--테이블 수정된걸로 수정
CREATE TABLE customers (
    idx NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    weight NUMBER(4, 1),
    age NUMBER(3),
    gender CHAR(1) CHECK (gender IN ('M', 'F')),
    height NUMBER(3)
);

