-- 테이블 삭제
DROP TABLE goal CASCADE CONSTRAINTS;

CREATE TABLE goal (
    idx NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    target_weight NUMBER(4, 1) NOT NULL,
    target_calories NUMBER(5) NOT NULL,
    record_date DATE NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customers(idx) ON DELETE CASCADE
);
SELECT * FROM goal;
-- goal테이블은 있는 경우

-- GOAL 테이블에 record_date 컬럼 추가
ALTER TABLE goal ADD record_date DATE;

-- null 값이 들어가지 않도록 제약 조건 추가
ALTER TABLE goal MODIFY record_date DATE NOT NULL;