-- ==========================
-- Password Recovery Table
-- 파일명: Recovery.sql
-- 테이블명: recovery
-- ==========================

CREATE TABLE recovery (
    idx           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   VARCHAR2(100)   NOT NULL,  -- customers.id (이메일)
    code          VARCHAR2(32)    NOT NULL,  -- enum: BIRTHPLACE / ELEMENTARY_SCHOOL / PET_NAME / MOTHER_NAME
    answer_hash   VARCHAR2(255)   NOT NULL,
    updated_at    TIMESTAMP       NOT NULL,
    CONSTRAINT uq_recovery_user_code UNIQUE (customer_id, code)
);

-- 필요 시 FK를 customers(id)에 연결 (고객 테이블 설계가 id UNIQUE 인 환경에서만 권장)
 ALTER TABLE recovery
   ADD CONSTRAINT fk_recovery_customer
   FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;

-- 확인
-- SELECT * FROM recovery;
